### ISSUE TITLE
Next steps plugin implementation

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/synapse-net#53]
- Handle resolution and rescaling correctly.
   - Read resolution from input file if possible (for mrc / rec).
   - Otherwise use optional input parameter in plugin.
   - Determine correct scaling based on average resolution model was trained on. (Need to aggregate this information).
   - Use the resolution in the distance measurement plugin.
- Upload all models and connect them in the plugin.
   - I will put them in a folder on our drive.
   - Aggregate the training information, including average resolution (see prev. point).
   - Distinguish the different vesicle models: `vesicles`, `vesicles_2d`, `vesicles_cryo` 
- Improve handling of tiling:
   - Use [get_default_tiling](https://github.com/computational-cell-analytics/synapse-net/blob/main/synaptic_reconstruction/inference/util.py#L376) to determine the tiling values in the plugin.
   - Update the tiling for the 2D model to be at least 512 x 512. 
- Use napari progressbars instead of tqdm to display activity in napari. This is simple by replacing `import tqdm` with
```python
try:
    from napari.utils import progress as tqdm
except ImportError:
    from tqdm import tqdm
```

**Comment by lufre1** [comment]
to use the napari progress bar we need to adapt https://github.com/constantinpape/torch-em/blob/4f7b180af8177da9f1c1c5b09b282f7c270a1249/torch_em/util/prediction.py#L7 in [torch-em](https://github.com/constantinpape/torch-em/tree/main)

**Comment by constantinpape** [comment]
> to use the napari progress bar we need to adapt https://github.com/constantinpape/torch-em/blob/4f7b180af8177da9f1c1c5b09b282f7c270a1249/torch_em/util/prediction.py#L7 in [torch-em](https://github.com/constantinpape/torch-em/tree/main)

Can you make a PR in `torch_em` for this?
