### ISSUE TITLE
Add mitochondria training script and info

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/synapse-net#63]
- [x] Add the training script to https://github.com/computational-cell-analytics/synapse-net/tree/main/scripts/cooper/training
- [x] Collect the info on how many tomograms, annotations and the resolution. I can do this, but I need the location of the tomograms on the cluster.

**Comment by lufre1** [comment]
The training script is here: 
- https://github.com/computational-cell-analytics/synapse-net/blob/main/scripts/cooper/training/train_mitochondria.py

and the location of the tomograms i sent you in PM
